### ISSUE TITLE
Usage in as an "OFX lint" manner?

### ISSUE THREAD

**Issue by phillbaker** [arolson101/ofx4js#2]
Hello! I've just begun exploring ofx4js and was curious if you thought it be possible to use this project in a way to "lint" OFX files - basically finding where in the file it deviates from the standard and shows those differences to the user.

It looks like the types may be helpful here - I was hoping to avoid writing a parser/grammar.

**Comment by arolson101** [comment]
This is a direct port of ofx4j, so anything that can do this should be able to do, but I didn't write ofx4j so I'm not sure what it can do.

**Comment by phillbaker** [comment]
Thanks!
