### ISSUE TITLE
ofx4js does not provide a module

### ISSUE THREAD

**Issue by mattgi** [arolson101/ofx4js#3]
Building a web app using Typescript, Yarn, and FuseBox, when I try to import ofx4js and use it, I receive the following error:

```
ofx4js does not provide a module
```

This occurs if I include two lines, and only presents when the `AggregateUnmarshaller` is added.

```
import { AggregateUnmarshaller, ResponseEnvelope } from "ofx4js";
```

```
const m = new AggregateUnmarshaller(ResponseEnvelope);
```

tsconfig:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "react",
    "lib": ["dom", "es2017", "esnext.asynciterable"],
    "plugins": [
      {
        "name": "typescript-styled-plugin"
      }
    ]
  }
}
```

Any ideas?

**Comment by arolson101** [comment]
Sorry, I don’t have any experience with fusebox.  I recently changed bundlers to use rollup, which I have very little experience with.  Perhaps there’s something with the rollup config?  I won’t be able to help you beyond advice, but if you figure it out I’d be happy to merge the fix.

**Comment by mattgi** [comment]
no worries, thanks for the reply :)
